### ISSUE TITLE
Featured picture not showing on post page

### ISSUE THREAD

**Issue by alezucca** [alezucca/londonandnewcastle#4]
![image](https://user-images.githubusercontent.com/19538358/72015026-e6dd6000-3258-11ea-858a-280d4c48ef65.png)

**Comment by marcotroisi** [comment]
Fixed in #8 

Featured picture is now shown on each post page: https://www.londonandnewcastle.com/posts/2020-01-13-schweickarts-bifurcated-hermeneutic/
